### ISSUE TITLE
Dealing with upstream PyQt upgrades

### ISSUE THREAD

**Issue by The-Compiler** [stlehmann/PyQt5-stubs#1]
Hey! I wanted to start a project like this [for a while](https://www.riverbankcomputing.com/pipermail/pyqt/2016-September/038070.html) (whoa, it's been two years already?!) but never got around to it. Now, as part of an [university project](https://lists.schokokeks.org/pipermail/qutebrowser-announce/2018-September/000051.html) I wanted to introduce mypy to [qutebrowser](https://qutebrowser.org/) and found this project.

This seems like a great start at making those stubs actually usable with mypy - thanks a lot for that!

I'll probably start contributing some pull requests over the next couple of days, for some issues I've seen when running mypy over qutebrowser.

I'm also wondering: What version of PyQt are those stubs based on? How do you intend to upgrade to newer versions? Maybe it'd be worthwhile to introduce an `upstream` branch with PyQt's files commited 1:1 for every PyQt release, and then those commits with the PyQt update can be cherry-picked to `master` in order to update the modified bindings?

**Comment by stlehmann** [comment]
Thanks for contacting me. I use PyQt5 a lot for my GUI projects and wanted to benefit from static type-checking. That's why I created this repository in the first place.

You can find the version of PyQt that the stubs are based on in the setup.py as defined by [PEP561](https://www.python.org/dev/peps/pep-0561/#stub-only-packages).

Of course it would be good to keep track of upstream changes but honestly I couldn' t bring up a good idea how to manage that efficiently. The thing is that the stub files returned when compiling PyQt5 are very buggy and there are a lot of changes to them that need to be made before they are actually usable.

**Comment by The-Compiler** [comment]
setup.py claims that it's based on PyQt 5.11.3 stubs, but that doesn't seem to be the case - things like enum numbers added in Qt 5.8 (say, `AA_DontCheckOpenGLContextThreadAffinity` in [Qt::ApplicationAttribute](http://doc.qt.io/qt-5/qt.html#ApplicationAttribute-enum)) aren't in the stubs, and the copyright also says 2016. It seems to me like they were generated around PyQt 5.7, not 5.11.

**Comment by stlehmann** [comment]
Mh, that might be the case...Honestly, I didn't watch the version so closely. But you' re right this needs to be taken care of in the future.

**Comment by stlehmann** [comment]
I updated all stubs to 5.11.3.

**Comment by stlehmann** [comment]
The original upstream stubs can be found on branch 5.11.3.org

**Comment by stlehmann** [comment]
> Maybe it'd be worthwhile to introduce an upstream branch with PyQt's files commited 1:1 for every PyQt release, and then those commits with the PyQt update can be cherry-picked to master in order to update the modified bindings?

Thanks for the suggestion. It turned out that worked well for updating to 5.11.3.
