### ISSUE TITLE
Make a release?  (after 5.15.2?)

### ISSUE THREAD

**Issue by altendky** [stlehmann/PyQt5-stubs#115]
It seems like it might be a reasonable idea to make a release.  There are plenty of bits to still work on but there have been a lot of changes.  Maybe after #113 makes it across with 5.15.2?  I'm not presently doing anything where I need this but if nothing else it gives us a chance to figure out how releases have been happening.  Any thoughts @stlehmann?

**Comment by stlehmann** [comment]
It seems like it is definetely the time for creating a new release after so many changes.

As stated in https://github.com/stlehmann/PyQt5-stubs/issues/23 I'm pulling out of the development process simply because I don't use PyQt5 anymore. I switched to PySide2 for the rare occasions I need a Desktop Application.

Even though I love to see this repository in good hands and the way it developed the last month seems to be the right path. I also think this to be the right time to transfer the ownership to this repository to someone involved in the actual development process. I'm thinking of one of the current maintainers here. Any volunteers? 😄

**Comment by altendky** [comment]
@BryceBeagle and @The-Compiler, should I just kick one out?

- [x] Wait for #130 to be merged
- [x] Wait for a successful build on `master`
- [x] Resolve #133 and update maintainer metadata
- [x] Work a release PR
  - [x] Remove `[unreleased]` from the changelog
  - [x] Get approval
  - [x] Tag as `5.15.2.0`
  - [x] Build artifacts for PyPI
    - `python -m build --sdist --wheel` I guess these days...
  - [x] Upload artifacts to PyPI
  - [x] Add `## 6.0.0.0 [unreleased]` to the changelog
    - Well, I mean, it'll presumably be 6.0.1 at least but...
  - [x] Merge PR

Good enough?  Or do you want a process etc etc setup first?

**Comment by BryceBeagle** [comment]
Yeah we're long overdue for a release, so even without a formalized release process I think we should make one. Thanks for taking the initiative here.

**Comment by altendky** [comment]
https://pypi.org/project/PyQt5-stubs/5.15.2.0/
