### ISSUE TITLE
Package looking for a new maintainer

### ISSUE THREAD

**Issue by stlehmann** [stlehmann/PyQt5-stubs#23]
I have created the PyQt5-stubs to add proper type annotations mainly for my personal PyQt5 applications without thinking much about a future-proof update strategy. It turns out that it is very cumbersome to take care of any version changes and keep the whole thing up-to-date with the upstream PyQt5 repository. Additionally I find myself using PySide2 more and more. PySide2 provides proper type annotations out of the box and has a more open licensing model. Because of this I decided to stop maintaining this package in the future. However, I would love to find a new maintainer that keeps this package alive. So if someone likes to take care of this package please contact me.

**Comment by The-Compiler** [comment]
I'm using PyQt5 and PyQt5-stubs for [my project](https://www.qutebrowser.org/) and will likely continue to do so for a while because PySide is way too unstable right now (see e.g. [this issue](https://bugreports.qt.io/browse/PYSIDE-239)).

So I'd definitely be interested! I think the best way forward is to try to contribute more to the [sip generator](https://www.riverbankcomputing.com/static/Docs/sip/introduction.html) upstream so it generates the correct bindings in the first place. Then hopefully at some point this repository can just be a collection of generated files! I think there are also upstream plans to rewrite more of sip in Python (rather than C), which might make this a bit easier as well.

However, I'm not going have the time to look at this for some more weeks, or possibly months. So if someone else steps up (or would like to help), that'd be great!

**Comment by sweethuman** [comment]
I'm all forward for this and what the person above me I support. It sounds pretty good and I'd love a new maintainer. I'd love to contribute more. I don't have the time or the knowledge of a maintainer. So I support you @The-Compiler

**Comment by stlehmann** [comment]
I personally didn't experience any issues with PySide2. But I guess that depends on the use-case. 

@The-Compiler, I would love to see the project in your hands. You make heavy use of PyQt5 with your project Qutebrowser and that is a good premise to ensure PyQt5-stubs meet the expactations of other users as well. 

I added you as a collaborator to grant you push access to the project.

**Comment by The-Compiler** [comment]
Thanks everyone for your trust! :heart: Just some advance warning: I'm unlikely to touch anything until early March or so, definitely too many things going on at the moment.

**Comment by stlehmann** [comment]
That's OK. I will try to keep the version up-to-date for now.

**Comment by altendky** [comment]
@BryceBeagle and @The-Compiler, perhaps we need a new PyQt or Qt organization to hold this repo?  Maybe pyqt5-tools would make sense there too?  `python-qt`?  Or maybe I'm thinking down the wrong path...

Huh, https://github.com/orgs/python-qt exists with no publicly visible members or repos.  Anyways, if we want then maybe we could get that.  I definitely plan on things I develop that aren't explicitly about PyQt to be compatible with PySide in the future hence considering 'Qt' over 'PyQt' for organization naming.

**Comment by altendky** [comment]
I can't come up with a good not-taken name for an organization for Python Qt related libraries (I expect to work with both PyQt5 and PySide2, hence generic Qt).  I did contact GitHub and they said they could send a message to the owner of the `python-qt` org so we'll see if they are interested in transferring or not.  If you want to pile on other ideas, have at.

**Comment by BryceBeagle** [comment]
Would `qt-python` work? It looks like it's available.

**Comment by altendky** [comment]
I hesitate a bit since in my head `python-` is the common way (attrs, trio, desert, pillow, poetry, etc) and anyone following the pattern will be lead not to a 404 but an existing but wrong place.  But yeah, thanks for the suggestion.  Maybe we end up there.

**Comment by altendky** [comment]
Hum, so qt-python is gone...  unless you grabbed it @BryceBeagle?  But, among actually available stuff...  any votes?  (and yes, the 'cutesy' stuff may just be bad and I should give up on coming up with some cool name)

- qties
- qooties
  - like little kid cooties, but qt
- cuties
- python-qt-tools
  - for better or worse, kinda close'ish to https://github.com/altendky/qt-tools

Please remind me what options I'm forgetting since I've been bad and not writing them down.  @stlehmann, please do share your opinion.  I don't want to transfer your project into an org you don't like.  At this point I'm ready to give up...  nothing super cool has come to my mind so we just need some name and to move forward.

**Comment by BryceBeagle** [comment]
Unfortunately it wasn't me who took `qt-python`.

This might give you some ideas:
![image](https://user-images.githubusercontent.com/5437880/104410586-893fbb80-551d-11eb-8104-24389db0514f.png)

I kinda like `electroqt` (pronounced electrocute) but that has nothing to do with Python. It's a stretch, but we could do `pyrseqt` (pronounced persecute)

**Comment by stlehmann** [comment]
I like python-qt-tools as it implies python tools concerning qt. :)

**Comment by altendky** [comment]
@BryceBeagle, so negative!  At least qooties is humorous (kinda, probably not really).  `:]`  @stlehmann, down to business serious mode...  Alrighty, I just created https://github.com/orgs/python-qt-tools now so it doesn't get sucked up (interesting timing on qt-python...).  If this doesn't magically inspire a super duper cooler name, then that's that.

Would each of @stlehmann, @BryceBeagle, and @The-Compiler please answer yes or no if you would like to be added as an owner on the org?  Actually, I think that @stlehmann  doesn't get a choice `:]`.  They have to be able to create repositories to transfer afaik.  But anyways, please all three answer yes or no for the long term.  Just to be clear, this doesn't imply you have any responsibility to develop, but having multiple people available to deal with issues if someone else goes AWOL or whatever and there's a promising new dev with time to revive the projects...

**Comment by BryceBeagle** [comment]
Sure, add me 👍

**Comment by altendky** [comment]
@stlehmann you will also need to add me as an owner on PyPI.  I will add others accordingly with python-qt-tools ownership.

My account: https://pypi.org/user/altendky/
Page for adding me: https://pypi.org/manage/project/PyQt5-stubs/collaboration/

You will also need to initiate the transfer.

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

If you have any questions I'll do what I can to get them answered.  Hopefully this ends up pretty quick for you.

**Comment by stlehmann** [comment]
Wow, that was a fast transfer. I wanted to answer here in the old place but was not allowed to do so because transfer was already done. So the news is: Repo is transferred ;D

Thanks @altendky for taking care of the organisation of the organisation. I also made you owner of the PyPi package. And yes, you can keep me added.

**Comment by The-Compiler** [comment]
Yay! :tada:

Feel free to add me as well - I'm The_Compiler on PyPI in case you want to add me there, too.

**Comment by altendky** [comment]
@BryceBeagle, I think the last invite is for you on PyPI.  What is your PyPI username?

**Comment by BryceBeagle** [comment]
@altendky I'm [`ignormies`](https://pypi.org/user/ignormies/) on PyPI

**Comment by altendky** [comment]
I suppose this is done and done.  Thank you @stlehmann for all your work creating and growing this project.  Maybe soon we'll find time to see what PyQt6 has in store for us.
