### ISSUE TITLE
Upstream branch workflow now

### ISSUE THREAD

**Issue by BryceBeagle** [stlehmann/PyQt5-stubs#90]
Now that `upstream` has been properly merged into `master`, what's the workflow for dealing with the non-stub files in the `master` branch? If I want to update the `README`, would we change it in `master` and cherrypick into `upstream`? The otherway around? 

I don't have much experience dealing with two parallel branches like this.

**Comment by altendky** [comment]
I'm not super sure.  The basic requirement is that `upstream` has the upstream stuff and whatever we need to support PRs to it.  It could be argued that the helpers for building the stubs belong in another project, but since they are here they would belong on the `upstream` branch.  (and I'm not concluded it is worth a separate project)  I guess docs that cover how to use that would belong in `upstream`.  So maybe the gist is to separate upstream-handling related files such as by moving the upstream instructions from the readme to a dedicate file?  If we can get the separation it becomes 'obvious' where to edit stuff.  Maybe?

(and yeah, I probably confused this with a couple commits `:[`)

**Comment by bluebird75** [comment]
Workflow is now described in 063ce8b76951e18e07a505f7cb56512b25c7d129
