### ISSUE TITLE
Automated PyPI releases

### ISSUE THREAD

**Issue by BryceBeagle** [stlehmann/PyQt5-stubs#96]
It would be nice if we could automate releases to PyPI whenever `master` is committed to. Right now the PyPI release has not been updated since May and is still on 5.14.2.

**Comment by The-Compiler** [comment]
I'm only aware of one project (hypothesis) doing this and I'm against it as it causes a lot of churn for nothing - especially when e.g. Linux distributions want to package things.

Why not make it very easy to trigger a release manually (say, by pushing a tag) and then do that every time when bunch of changes have been done?

**Comment by BryceBeagle** [comment]
The other project I contribute to (https://github.com/strawberry-graphql/strawberry) does this, and I find it pretty convenient, although I do see the downsides. A manually triggered, but still automated, release would be a good middleground.

**Comment by The-Compiler** [comment]
For GitHub Actions, here's what I do for some projects: https://github.com/The-Compiler/pytest-mccabe/blob/master/.github/workflows/main.yml

No idea for Travis CI - IMHO it'd be good to switch to GHA instead, due to the broad adoption, way better performance and the fact that it seems actively maintained than Travis CI.

**Comment by altendky** [comment]
Also as I understand it there are platform specific Qt libraries we don't handle yet (and should (and Travis doesn't really do anything but Linux for Python)).  So yeah, I expect GHA in the future at some point.  I personally have a little script that checks for a tag and pushes  to PyPI to handle that bit.  It is CI agnostic because, well, we always end up hopping CI systems.  Right?  I use versioneer for Git tag controlled versioning.  I haven't experimented with release every master commit but do appreciate a release consisting of `git tag vX; git push --tags`.  Admittedly, those projects don't have release notes and I don't have a solution for that quite yet (maybe reno but they depend on certain branching structures that I haven't fully understood yet).  And *sigh*.  I just now see there's a changelog to be updated...  Hmm...  time to require something more of each PR I guess, and to catch that changelog up.  And maybe towncrier or...?  So much stuff...

**Comment by bluebird75** [comment]
I consider the current manual process as good enough. So closing this issue.
